{
"Algorithm" : "DecisionTree",
"parameters" : {"max_depth":3, "criterion":"gini"},
"split_ratio" : 0.25,
"ML_Features" : "Onboard Wifi Service, Onboard Dining Service, Onboard Entertainment, Gender, Date of Birth, Online Check-in, Cabin Comfort, Cabin service, Baggage handling, Port Check-in Service, Onboard Service, Cleanliness, Cruise Name, Cruise Distance, WiFi, Dining, Entertainment"
}